version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:11.10.0
    working_directory: ~/pvamshi/blog
    steps:
      - checkout
      # Bundle install dependencies
      # - run: bundle install --path vendor/bundle

      # Database setup
      - run: npx build

      #- run:
      #    name: Run tests
      #    command: rake

  deploy:
    machine:
        enabled: true
    working_directory: ~/pvamshi/blog
    environment:
      #HEROKU_APP: "sleepy-refuge-55486"
    steps:
      - checkout
      # - run:
      #     name: Setup Heroku
      #     command: bash .circleci/setup-heroku.sh

      - run: npx deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          
